<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <Version>1.0.0-beta3</Version>
    <Authors>SuuBro</Authors>
    <Company />
    <Description>Component Parameterisation for C#</Description>
    <Copyright>Copyright 2018</Copyright>
    <RepositoryUrl>https://github.com/SuuBro/Paramulate</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <PackageTags>Paramulate Parameterisation Parameters Arguments Configuration Options Commandline CLI csharp</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ImpromptuInterface" Version="8.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
